In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
Dataset = pd.read_csv("Preprocessed_ecommerce.csv")

Dataset

InvoiceNo  StockCode  Description  Quantity      InvoiceDate  \
0         536365       3438         3636         6   12/1/2010 8:26   
1         536365       2739         3643         6   12/1/2010 8:26   
2         536365       2975          854         8   12/1/2010 8:26   
3         536365       2919         1765         6   12/1/2010 8:26   
4         536365       2918         2707         6   12/1/2010 8:26   
...          ...        ...          ...       ...              ...   
541792    581587       1492         2199        12  12/9/2011 12:50   
541793    581587       1768          695         6  12/9/2011 12:50   
541794    581587       2110          701         4  12/9/2011 12:50   
541795    581587       2111          700         4  12/9/2011 12:50   
541796    581587       1059          271         3  12/9/2011 12:50   

        UnitPrice  Country  Total_Price  Best_Selling  
0            2.55       36        15.30             1  
1            3.39       36        20.34             1  
2            2.75       36        22.00             1  
3            3.39       36        20.34             1  
4            3.39       36        20.34             1  
...           ...      ...          ...           ...  
541792       0.85       13        10.20             1  
541793       2.10       13        12.60             1  
541794       4.15       13        16.60             1  
541795       4.15       13        16.60             1  
541796       4.95       13        14.85             1  

[541797 rows x 9 columns]

In [3]:
Independent = Dataset[["Description", "Quantity", "UnitPrice"]]
Dependent = Dataset[["Best_Selling"]]

In [4]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(Independent, Dependent, test_size = 0.2, random_state = 0)

In [5]:
from sklearn.ensemble import RandomForestClassifier
RFClassifier = RandomForestClassifier()
RFClassifier.fit(x_train, y_train)

C:\Users\Sai Vennela Jagadesh\anaconda3\envs\AIML\Lib\site-packages\sklearn\base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier()

In [6]:
RFImportance = RFClassifier.feature_importances_
RFImportance

array([0.02752617, 0.61022346, 0.36225037])

In [7]:
y_pred = RFClassifier.predict(x_test)

In [8]:
from sklearn.metrics import confusion_matrix
RFcm = confusion_matrix(y_test, y_pred)
RFcm

array([[53884,     2],
       [    2, 54472]], dtype=int64)

In [9]:
# We are creating report

from sklearn.metrics import classification_report
RFResult = classification_report(y_test, y_pred)

In [10]:
print(RFResult)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     53886
           1       1.00      1.00      1.00     54474

    accuracy                           1.00    108360
   macro avg       1.00      1.00      1.00    108360
weighted avg       1.00      1.00      1.00    108360



In [11]:
from sklearn.neighbors import KNeighborsClassifier
KNClassifier = KNeighborsClassifier()
KNClassifier.fit(x_train, y_train)

C:\Users\Sai Vennela Jagadesh\anaconda3\envs\AIML\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [12]:
y_pred = KNClassifier.predict(x_test)

In [13]:
from sklearn.metrics import confusion_matrix
KNcm = confusion_matrix(y_test, y_pred)
KNcm

array([[53437,   449],
       [  705, 53769]], dtype=int64)

In [14]:
# We are creating report

from sklearn.metrics import classification_report
KNResult = classification_report(y_test, y_pred)

print(KNResult)

              precision    recall  f1-score   support

           0       0.99      0.99      0.99     53886
           1       0.99      0.99      0.99     54474

    accuracy                           0.99    108360
   macro avg       0.99      0.99      0.99    108360
weighted avg       0.99      0.99      0.99    108360



In [15]:
from sklearn.linear_model import LogisticRegression
LRClassifier = LogisticRegression()
LRClassifier.fit(x_train, y_train)

C:\Users\Sai Vennela Jagadesh\anaconda3\envs\AIML\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [16]:
y_pred = LRClassifier.predict(x_test)

In [17]:
from sklearn.metrics import confusion_matrix
LRcm = confusion_matrix(y_test, y_pred)
LRcm

array([[47722,  6164],
       [19175, 35299]], dtype=int64)

In [18]:
from sklearn.metrics import classification_report
LRResult = classification_report(y_test, y_pred)

print(LRResult)

              precision    recall  f1-score   support

           0       0.71      0.89      0.79     53886
           1       0.85      0.65      0.74     54474

    accuracy                           0.77    108360
   macro avg       0.78      0.77      0.76    108360
weighted avg       0.78      0.77      0.76    108360



In [19]:
from sklearn.naive_bayes import GaussianNB
GClassifier = GaussianNB()
GClassifier.fit(x_train, y_train)

C:\Users\Sai Vennela Jagadesh\anaconda3\envs\AIML\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [20]:
y_pred = GClassifier.predict(x_test)

In [21]:
from sklearn.metrics import confusion_matrix
Gcm = confusion_matrix(y_test, y_pred)
Gcm

array([[   54, 53832],
       [  168, 54306]], dtype=int64)

In [22]:
from sklearn.metrics import classification_report
GResult = classification_report(y_test, y_pred)

print(GResult)

              precision    recall  f1-score   support

           0       0.24      0.00      0.00     53886
           1       0.50      1.00      0.67     54474

    accuracy                           0.50    108360
   macro avg       0.37      0.50      0.33    108360
weighted avg       0.37      0.50      0.34    108360



In [23]:
from sklearn.naive_bayes import BernoulliNB
BClassifier = BernoulliNB()
BClassifier.fit(x_train, y_train)

C:\Users\Sai Vennela Jagadesh\anaconda3\envs\AIML\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


BernoulliNB()

In [24]:
y_pred = BClassifier.predict(x_test)

In [25]:
from sklearn.metrics import confusion_matrix
Bcm = confusion_matrix(y_test, y_pred)
Bcm

array([[ 2319, 51567],
       [    2, 54472]], dtype=int64)

In [26]:
from sklearn.metrics import classification_report
BResult = classification_report(y_test, y_pred)

print(BResult)

              precision    recall  f1-score   support

           0       1.00      0.04      0.08     53886
           1       0.51      1.00      0.68     54474

    accuracy                           0.52    108360
   macro avg       0.76      0.52      0.38    108360
weighted avg       0.76      0.52      0.38    108360



In [27]:
from sklearn.tree import DecisionTreeClassifier
DTClassifier = DecisionTreeClassifier()
DTClassifier.fit(x_train, y_train)

DecisionTreeClassifier()

In [28]:
y_pred = DTClassifier.predict(x_test)

In [29]:
from sklearn.metrics import confusion_matrix
DTcm = confusion_matrix(y_test, y_pred)
DTcm

array([[53885,     1],
       [    1, 54473]], dtype=int64)

In [30]:
from sklearn.metrics import classification_report
DTResult = classification_report(y_test, y_pred)

print(DTResult)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     53886
           1       1.00      1.00      1.00     54474

    accuracy                           1.00    108360
   macro avg       1.00      1.00      1.00    108360
weighted avg       1.00      1.00      1.00    108360



In [31]:
import pickle

filename = "ecommerce_Best_Model.sav"

In [32]:
pickle.dump(RFClassifier, open("ecommerce_Best_Model.sav", "wb"))

In [33]:
Loaded_Model = pickle.load(open("ecommerce_Best_Model.sav", "rb"))

In [34]:
Predict = Loaded_Model.predict([[271, 3, 4.95]])

C:\Users\Sai Vennela Jagadesh\anaconda3\envs\AIML\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [35]:
Predict

array([1], dtype=int64)